/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package reactor.kitchen;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void appHasAGreeting() {
        Inventory inventory = new Inventory();
        App classUnderTest = new App(new OrderHandler(new CookService(inventory)));
        assertNotNull(classUnderTest);
    }
}
